POST http://127.0.0.1:3000/api/v1/users HTTP/1.1
Content-Type: application/json

{
    
       "name": "Alex Junior",
    "birthDate": "1997-04-29",
    "email": "cleitinnajuju.anp@gmail.com",
    "password": "123456789",
    "gender": "Male"
  
}
### 

POST http://127.0.0.1:3000/api/v1/login HTTP/1.1
Content-Type: application/json

{
   "email": "cleitinnajuju.anp@gmail.com",
    "password": "123456789" 
}

###

GET http://127.0.0.1:3000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlY2YyZTMwZC02Y2NmLTQzNjQtODZkYS00NWVmMzc5MGNiYzYiLCJzdWIiOiJhNDkwNTM0My03YjIyLTQzMTgtODkxYi1jYTkwMGNmM2ViZTMiLCJpYXQiOjE3MDI1MTUwMzUsImVtYWlsIjoiY2xlaXRpbm5hanVqdS5hbnBAZ21haWwuY29tIiwiZXhwIjoxNzAyNTIyMjM1fQ.u8NmtIVH7b-G_txdzRtLu-qFOYG5rbebv1gJmz2KxO4
###


GET http://127.0.0.1:3000/api/v1/users/1bbb610946-a302-43f5-9da5-f299b177b80f HTTP/1.1
###
